setwd("C:\\Users\\A580489\\Documents\\R\\Coursera\\Exploratory Data Analysis\\exdata-data-household_power_consumption")
data <- read.table("household_power_consumption.txt",sep=";", header=T,stringsAsFactors=F)
data$Date <- as.Date(data$Date, format = "%d/%m/%Y") 
data2 <- data[c(which(data$Date=="2007-02-01"),which(data$Date=="2007-02-02")),]
data2$DateTime <- strptime(paste(data2$Date, data2$Time, sep=" "), format = "%Y-%m-%d %H:%M:%S")
png("Plot4.png",width=480,height=480)
par(mfrow = c(2,2),pty="s")
plot(data2$DateTime, data2$Global_active_power, type="l",xlab="",ylab="Global Active Power (kilowatts)" )
plot(data2$DateTime,data2$Voltage, type="l",xlab="datetime",ylab="Voltage")
plot(data2$DateTime, data2$Sub_metering_1, type="l",col = "black",xlab="",ylab="Energy Sub Metering" )
lines(data2$DateTime,data2$Sub_metering_2, type="l",col = "red")
lines(data2$DateTime,data2$Sub_metering_3, type="l",col = "blue")
plot(data2$DateTime, data2$Global_reactive_power, type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
